# Generated by Django 2.2.16 on 2022-11-04 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221104_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='genretitle',
            old_name='genre',
            new_name='genre_id',
        ),
        migrations.RenameField(
            model_name='genretitle',
            old_name='title',
            new_name='title_id',
        ),
        migrations.AlterField(
            model_name='genretitle',
            name='genre_id',
            field=models.ForeignKey(db_column='genre_id', help_text='Жанр произведения', on_delete=django.db.models.deletion.CASCADE, related_name='genre', to='reviews.Genres', verbose_name='Жанр'),
        ),
        migrations.AlterField(
            model_name='genretitle',
            name='title_id',
            field=models.ForeignKey(db_column='title_id', help_text='Произведение определенного жанра', on_delete=django.db.models.deletion.CASCADE, related_name='title', to='reviews.Titles', verbose_name='Произведение'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(blank=True, db_column='category', help_text='Категория, к которой относится произведение', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='category', to='reviews.Categories', verbose_name='Категория'),
        ),
    ]
