# Generated by Django 2.2.16 on 2022-11-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20221104_2202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ('-pub_date',)},
        ),
        migrations.AddField(
            model_name='comments',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default='2022-11-04 00:01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, default='2022-11-04 00:01'),
            preserve_default=False,
        ),
    ]
